export const KitBaza="1 adeziv Flawless 5g, 1 Primer, 1 Placuta Holograma, 2 Casete Extensii Gene - Velvet & Foxy, 2 Pensete, Banda 3M, 1 Remover, 10 Patch-uri, set microbrush-uri, set aplicatoare"
export const KitEfecte="1 adeziv Rapid 5g, 1 Primer, 1 Placuta Holograma, 1 Caseta Mix Extensii Gene, 2 Pensete,1 Remover"

export const PREFIXES=[
    { code: "+40", name: "Romania" },
    { code: "+49", name: "Germany" },
    { code: "+33", name: "France" },
    { code: "+1", name: "United States" },
    { code: "+44", name: "United Kingdom" },
    { code: "+39", name: "Italy" },
    { code: "+34", name: "Spain" },
    { code: "+7", name: "Russia" },
    { code: "+86", name: "China" },
    { code: "+91", name: "India" },
    { code: "+81", name: "Japan" },
    { code: "+61", name: "Australia" },
    { code: "+55", name: "Brazil" },
    { code: "+27", name: "South Africa" },
    { code: "+82", name: "South Korea" },
    { code: "+47", name: "Norway" },
    { code: "+46", name: "Sweden" },
    { code: "+31", name: "Netherlands" },
    { code: "+41", name: "Switzerland" },
    { code: "+32", name: "Belgium" },
    { code: "+420", name: "Czech Republic" },
    { code: "+48", name: "Poland" },
    { code: "+351", name: "Portugal" },
    { code: "+30", name: "Greece" },
    { code: "+90", name: "Turkey" },
    { code: "+213", name: "Algeria" },
    { code: "+216", name: "Tunisia" },
    { code: "+20", name: "Egypt" },
    { code: "+62", name: "Indonesia" },
    { code: "+63", name: "Philippines" },
    { code: "+64", name: "New Zealand" },
    { code: "+94", name: "Sri Lanka" },
    { code: "+598", name: "Uruguay" },
    { code: "+58", name: "Venezuela" },
    { code: "+234", name: "Nigeria" },
    { code: "+251", name: "Ethiopia" },
    { code: "+254", name: "Kenya" },
    { code: "+233", name: "Ghana" },
    { code: "+92", name: "Pakistan" },
    { code: "+880", name: "Bangladesh" },
    { code: "+66", name: "Thailand" },
    { code: "+972", name: "Israel" },
    { code: "+351", name: "Portugal" },
    { code: "+358", name: "Finland" },
    { code: "+372", name: "Estonia" },
    { code: "+371", name: "Latvia" },
    { code: "+370", name: "Lithuania" },
    { code: "+387", name: "Bosnia and Herzegovina" },
    { code: "+389", name: "North Macedonia" },
    { code: "+381", name: "Serbia" },
    { code: "+385", name: "Croatia" },
    { code: "+386", name: "Slovenia" },
    { code: "+994", name: "Azerbaijan" },
    { code: "+374", name: "Armenia" },
    { code: "+995", name: "Georgia" },
    { code: "+380", name: "Ukraine" },
    { code: "+371", name: "Latvia" },
    { code: "+373", name: "Moldova" },
    { code: "+359", name: "Bulgaria" },
    { code: "+372", name: "Estonia" },
    { code: "+256", name: "Uganda" },
    { code: "+254", name: "Kenya" },
    { code: "+258", name: "Mozambique" },
    { code: "+244", name: "Angola" },
    { code: "+263", name: "Zimbabwe" },
  ];